### CREATE
POST /users HTTP/1.1
Host: localhost:9999
Content-Type: application/json

{
    "email": "1@gmail.com",
    "password": "hsadfa"
}

### GET ALL USERS
GET /users HTTP/1.1
Host: localhost:9999

### GET ALL USERS BY ID
GET /users/2 HTTP/1.1
Host: localhost:9999

### UPDATE USER
PATCH /users/1 HTTP/1.1
Host: localhost:9999
Content-Type: application/json

{
    "email": "berubah@gmail.com",
    "password": "berubah"
}

### DELETE USER
DELETE  /users/1 HTTP/1.1
Host: localhost:9999